-- Subqueries
SELECT * FROM EMPLOYEE_INFO;

-- Identify Smith's salary
SELECT SALARY 
FROM EMPLOYEE_INFO 
WHERE LAST_NAME = 'Smith';

-- Compare to see who has a lower salary than Smith's
SELECT LAST_NAME, SALARY
FROM EMPLOYEE_INFO
WHERE SALARY < (SELECT SALARY FROM EMPLOYEE_INFO WHERE LAST_NAME = 'Smith');

-- Multiple row subqueries
-- Identify salary of employees in dept 20
SELECT LAST_NAME, SALARY 
FROM EMPLOYEE_INFO
WHERE DEPARTMENT_ID = 20;

-- < ANY
SELECT EMPLOYEE_ID, LAST_NAME, JOB_ID, SALARY 
FROM EMPLOYEE_INFO
WHERE SALARY < ANY (SELECT SALARY FROM EMPLOYEE_INFO WHERE DEPARTMENT_ID = 20);

-- > ANY
SELECT EMPLOYEE_ID, LAST_NAME, JOB_ID, SALARY 
FROM EMPLOYEE_INFO
WHERE SALARY > ANY (SELECT SALARY FROM EMPLOYEE_INFO WHERE DEPARTMENT_ID = 20);

-- < ALL
SELECT EMPLOYEE_ID, LAST_NAME, JOB_ID, SALARY 
FROM EMPLOYEE_INFO
WHERE SALARY < ALL (SELECT SALARY FROM EMPLOYEE_INFO WHERE DEPARTMENT_ID = 20);

-- > ALL
SELECT EMPLOYEE_ID, LAST_NAME, JOB_ID, SALARY 
FROM EMPLOYEE_INFO
WHERE SALARY > ALL (SELECT SALARY FROM EMPLOYEE_INFO WHERE DEPARTMENT_ID = 20);

-- IN
SELECT EMPLOYEE_ID, LAST_NAME, JOB_ID, SALARY 
FROM EMPLOYEE_INFO
WHERE SALARY IN (SELECT SALARY FROM EMPLOYEE_INFO WHERE DEPARTMENT_ID = 20);

-- NOT IN
SELECT EMPLOYEE_ID, LAST_NAME, JOB_ID, SALARY 
FROM EMPLOYEE_INFO
WHERE SALARY NOT IN (SELECT SALARY FROM EMPLOYEE_INFO WHERE DEPARTMENT_ID = 20);

-- EXIST
SELECT EMPLOYEE_ID, LAST_NAME, JOB_ID, SALARY 
FROM EMPLOYEE_INFO e
WHERE EXISTS (SELECT 1 FROM EMPLOYEE_INFO WHERE DEPARTMENT_ID = 20 AND e.SALARY=SALARY);