-- Subqueries
SELECT * FROM EMPLOYEE_INFO;

-- Identify Smith's salary
SELECT SALARY 
FROM EMPLOYEE_INFO 
WHERE LAST_NAME = 'Smith';

-- Compare to see who has a lower salary than Smith's
SELECT LAST_NAME, SALARY
FROM EMPLOYEE_INFO
WHERE SALARY < (SELECT SALARY FROM EMPLOYEE_INFO WHERE LAST_NAME = 'Smith');

-- Multiple row subqueries
-- Identify salary of employees in dept 20
SELECT LAST_NAME, SALARY 
FROM EMPLOYEE_INFO
WHERE DEPARTMENT_ID = 20;

-- < ANY
SELECT EMPLOYEE_ID, LAST_NAME, JOB_ID, SALARY 
FROM EMPLOYEE_INFO
WHERE SALARY < ANY (SELECT SALARY FROM EMPLOYEE_INFO WHERE DEPARTMENT_ID = 20);

-- > ANY
SELECT EMPLOYEE_ID, LAST_NAME, JOB_ID, SALARY 
FROM EMPLOYEE_INFO
WHERE SALARY > ANY (SELECT SALARY FROM EMPLOYEE_INFO WHERE DEPARTMENT_ID = 20);

-- ALL

-- IN / NOT IN

-- EXIST